CREATE TABLE [MonAn] (
	MaMA varchar(5) NOT NULL,
	Ten varchar(50) NOT NULL,
	gia integer NOT NULL,
	MaLoai varchar(5) NOT NULL,
	Mota varchar(255) NOT NULL,
	MaDS varchar(5) NOT NULL,
  CONSTRAINT [PK_MONAN] PRIMARY KEY CLUSTERED
  (
  [MaMA] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Hinh] (
	MaHinh varchar(5) NOT NULL,
	MaMA varchar(5) NOT NULL,
	DuongDan varchar(255) NOT NULL,
  CONSTRAINT [PK_HINH] PRIMARY KEY CLUSTERED
  (
  [MaHinh] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [LoaiMA] (
	MaLoai varchar(5) NOT NULL,
	TenLoai varchar(50) NOT NULL,
  CONSTRAINT [PK_LOAIMA] PRIMARY KEY CLUSTERED
  (
  [MaLoai] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [DanhSachMA] (
	MaDS varchar(5) NOT NULL,
	Ngay date NOT NULL,
	ChiNhanh varchar(255) NOT NULL,
  CONSTRAINT [PK_DANHSACHMA] PRIMARY KEY CLUSTERED
  (
  [MaDS] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [ChiTietDS] (
	MaCT varchar(5) NOT NULL,
	MaMA varchar(5) NOT NULL,
	MaDS varchar(5) NOT NULL,
  CONSTRAINT [PK_CHITIETDS] PRIMARY KEY CLUSTERED
  (
  [MaCT] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [HoaDon] (
	MaHD varchar(5) NOT NULL,
	TongTien float NOT NULL,
	NgayMua date NOT NULL,
	TinhTrang binary NOT NULL,
  CONSTRAINT [PK_HOADON] PRIMARY KEY CLUSTERED
  (
  [MaHD] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [ChiTietHD] (
	MaCTHD varchar(5) NOT NULL,
	MaMA varchar(5) NOT NULL,
	SoLuong integer NOT NULL,
	TinhTrang integer NOT NULL,
	MaHD integer NOT NULL,
  CONSTRAINT [PK_CHITIETHD] PRIMARY KEY CLUSTERED
  (
  [MaCTHD] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
ALTER TABLE [MonAn] WITH CHECK ADD CONSTRAINT [MonAn_fk0] FOREIGN KEY ([MaLoai]) REFERENCES [LoaiMA]([MaLoai])
ON UPDATE CASCADE
GO
ALTER TABLE [MonAn] CHECK CONSTRAINT [MonAn_fk0]
GO

ALTER TABLE [Hinh] WITH CHECK ADD CONSTRAINT [Hinh_fk0] FOREIGN KEY ([MaMA]) REFERENCES [MonAn]([MaMA])
ON UPDATE CASCADE
GO
ALTER TABLE [Hinh] CHECK CONSTRAINT [Hinh_fk0]
GO



ALTER TABLE [ChiTietDS] WITH CHECK ADD CONSTRAINT [ChiTietDS_fk0] FOREIGN KEY ([MaMA]) REFERENCES [MonAn]([MaMA])
ON UPDATE CASCADE
GO
ALTER TABLE [ChiTietDS] CHECK CONSTRAINT [ChiTietDS_fk0]
GO
ALTER TABLE [ChiTietDS] WITH CHECK ADD CONSTRAINT [ChiTietDS_fk1] FOREIGN KEY ([MaDS]) REFERENCES [DanhSachMA]([MaDS])
ON UPDATE CASCADE
GO
ALTER TABLE [ChiTietDS] CHECK CONSTRAINT [ChiTietDS_fk1]
GO


ALTER TABLE [ChiTietHD] WITH CHECK ADD CONSTRAINT [ChiTietHD_fk0] FOREIGN KEY ([MaMA]) REFERENCES [MonAn]([MaMA])
ON UPDATE CASCADE
GO
ALTER TABLE [ChiTietHD] CHECK CONSTRAINT [ChiTietHD_fk0]
GO
ALTER TABLE [ChiTietHD] WITH CHECK ADD CONSTRAINT [ChiTietHD_fk1] FOREIGN KEY ([MaHD]) REFERENCES [HoaDon]([MaHD])
ON UPDATE CASCADE
GO
ALTER TABLE [ChiTietHD] CHECK CONSTRAINT [ChiTietHD_fk1]
GO

